name: Commit Linter

description: Lints Pull Request commit messages with commitlint
author: Ondrej Winter

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@v5
